quad:
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 100

  joint_motor_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
          - joint_prop_1
          - joint_prop_2
          - joint_prop_3
          - joint_prop_4
      gains:
          joint_prop_1: {p: 10000, i: 1, d: 1000}
          joint_prop_2: {p: 10000, i: 1, d: 1000}
          joint_prop_3: {p: 10000, i: 1, d: 1000}
          joint_prop_4: {p: 10000, i: 1, d: 1000}
